### ISSUE TITLE
Server-side error after redeploy

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#2110]
## Description
Sometimes after deploying a new version, there is some sort of bug that causes logins to fail. On the server, an error is thrown which seems to be related. Clearing cookies before trying to log in seems to work.

## Steps to reproduce
This might be difficult for just anyone to reproduce, unless you have a server that can run a production version of the app behind nginx.

1. Deploy, run and use an existing version of the app
2. Deploy a new version of the docker image
3. Browse to /organize/1
4. Log in

### Expected Behaviour
Should return to /organize/1

### Actual Behaviour
Stops at /?code=<oauth-code-goes-here> with an nginx server error indicating that the NEXT app did not respond. The output below is traced by the NEXT server:

```
Error: Failed to find Server Action "null". This request might be from an older or newer deployment. Original error: Invariant: Missing 'next-action' header.
    at rv (/var/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:1666)
    at /var/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:7002
    at AsyncLocalStorage.run (node:async_hooks:338:14)
    at rg (/var/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:6317)
    at rz (/var/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:24715)
    at /var/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:27397
    at AsyncLocalStorage.run (node:async_hooks:338:14)
    at Object.wrap (/var/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:13:16207)
    at /var/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:27287
    at AsyncLocalStorage.run (node:async_hooks:338:14)
```

## Screenshots (if you have any)
None

**Comment by richardolsson** [comment]
I believe I have solved this, and that the problem was actually with the nginx configuration. Will reopen if the bug reappears.
