### ISSUE TITLE
Export View as CSV

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#480]
## Description
It would be nice to be able to download a view as a CSV.

## Relevant Job Stories
None

## Prerequisites
This task can be started without prerequisites.

## Requirements
- [ ] There should be a link somewhere to download CSV
- [ ] Clicking that link should open a modal
  - [ ] The modal should have text recommending the user not to export data for data protection reasons
  - [ ] The modal should allow the user to define a name for the file
  - [ ] The default name of the downloaded CSV file should reflect the name of the view and include a timestamp
- [ ] The CSV file should respect filters and sorting
- [ ] The Avatar column should be excluded
- [ ] The export should always include a Zetkin ID column

## Possible implementations
Either use the [toolbar](https://v4.mui.com/components/data-grid/export/) or [`apiRef`](https://v4.mui.com/components/data-grid/export/#apiref) from the MUI grid.

## Design specifications
See wireframe below for where the export should go in the toolbar. However, I think this might require some further discussion as this is the second ellipsis menu on the page (besides the one in the header).

![image](https://user-images.githubusercontent.com/550212/142988338-a92969cf-9572-4423-bf02-220d5a5b5530.png)

## Open questions
* Where do we put this, so as to not cause confusion with the double ellipsis menus?

**Comment by bimtauer** [comment]
I can try to have a go at this :)

**Comment by richardolsson** [comment]
Sounds great @bimtauer!

In the wireframes there are two "ellipsis menus" which is not ideal. I think we should put this in the "ellipsis menu" that has already been implemented, up in the top right corner.

![image](https://user-images.githubusercontent.com/550212/148694145-c73051c5-8343-48f3-8f80-db2a20cef70f.png)

**Comment by bimtauer** [comment]
On it: 
![image](https://user-images.githubusercontent.com/30375389/148694223-487aae33-ceaa-4292-8395-18f0e51bca13.png)

**Comment by bimtauer** [comment]
I found time to pick this up again but there seemed to be an issue with the dev database. Navigating to for example `localhost:3000//organize/1/people/views/3` or any other view index that I tried returned 404. I tried syncing with upstream main, assuming that maybe some new breaking changes had been introduced but it looks like main currently doesn't. Running `yarn devserver` on `main` yields:

```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /home/tim/Documents/Personal/app.zetkin.org/.env.development
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Using external babel configuration from /home/tim/Documents/Personal/app.zetkin.org/.babelrc
event - compiled successfully
event - build page: /404
wait  - compiling...
event - compiled successfully
Error: [@formatjs/intl Error MISSING_TRANSLATION] Missing message: "misc.ConfirmDialog.defaultTitle" for locale "en", using id as fallback. 

    at new MissingTranslationError (/home/tim/Documents/Personal/app.zetkin.org/node_modules/@formatjs/intl/src/error.js:79:28)
    at formatMessage (/home/tim/Documents/Personal/app.zetkin.org/node_modules/@formatjs/intl/src/message.js:68:21)
    at formatMessage (/home/tim/Documents/Personal/app.zetkin.org/node_modules/react-intl/src/components/provider.js:48:39)
    at ZetkinConfirmDialog (webpack-internal:///./src/components/ZetkinConfirmDialog.tsx:32:26)
    at processChild (/home/tim/Documents/Personal/app.zetkin.org/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/home/tim/Documents/Personal/app.zetkin.org/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/home/tim/Documents/Personal/app.zetkin.org/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/home/tim/Documents/Personal/app.zetkin.org/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToString (/home/tim/Documents/Personal/app.zetkin.org/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at renderPage (/home/tim/Documents/Personal/app.zetkin.org/node_modules/next/dist/server/render.js:596:45) {
  code: 'MISSING_TRANSLATION',
  descriptor: { id: 'misc.ConfirmDialog.defaultTitle' }
}
Error: [@formatjs/intl Error MISSING_TRANSLATION] Missing message: "misc.ConfirmDialog.defaultWarningText" for locale "en", using id as fallback. 

    at new MissingTranslationError (/home/tim/Documents/Personal/app.zetkin.org/node_modules/@formatjs/intl/src/error.js:79:28)
    at formatMessage (/home/tim/Documents/Personal/app.zetkin.org/node_modules/@formatjs/intl/src/message.js:68:21)
    at formatMessage (/home/tim/Documents/Personal/app.zetkin.org/node_modules/react-intl/src/components/provider.js:48:39)
    at ZetkinConfirmDialog (webpack-internal:///./src/components/ZetkinConfirmDialog.tsx:37:37)
    at processChild (/home/tim/Documents/Personal/app.zetkin.org/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/home/tim/Documents/Personal/app.zetkin.org/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/home/tim/Documents/Personal/app.zetkin.org/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/home/tim/Documents/Personal/app.zetkin.org/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToString (/home/tim/Documents/Personal/app.zetkin.org/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at renderPage (/home/tim/Documents/Personal/app.zetkin.org/node_modules/next/dist/server/render.js:596:45) {
  code: 'MISSING_TRANSLATION',
  descriptor: { id: 'misc.ConfirmDialog.defaultWarningText' }
}
Error: [@formatjs/intl Error MISSING_TRANSLATION] Missing message: "misc.ConfirmDialog.button" for locale "en", using id as fallback. 

    at new MissingTranslationError (/home/tim/Documents/Personal/app.zetkin.org/node_modules/@formatjs/intl/src/error.js:79:28)
    at formatMessage (/home/tim/Documents/Personal/app.zetkin.org/node_modules/@formatjs/intl/src/message.js:68:21)
    at formatMessage (/home/tim/Documents/Personal/app.zetkin.org/node_modules/react-intl/src/components/provider.js:48:39)
    at ZetkinConfirmDialog (webpack-internal:///./src/components/ZetkinConfirmDialog.tsx:52:26)
    at processChild (/home/tim/Documents/Personal/app.zetkin.org/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/home/tim/Documents/Personal/app.zetkin.org/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/home/tim/Documents/Personal/app.zetkin.org/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/home/tim/Documents/Personal/app.zetkin.org/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToString (/home/tim/Documents/Personal/app.zetkin.org/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at renderPage (/home/tim/Documents/Personal/app.zetkin.org/node_modules/next/dist/server/render.js:596:45) {
  code: 'MISSING_TRANSLATION',
  descriptor: { id: 'misc.ConfirmDialog.button' }
}
event - build page: /organize/[orgId]/people/views/[viewId]
wait  - compiling...
error - ./src/components/views/ViewDataTable/index.tsx:1:0
Module not found: Can't resolve 'lodash.isequal'
> 1 | import isEqual from 'lodash.isequal';
  2 | import { makeStyles } from '@material-ui/core';
  3 | import NProgress from 'nprogress';
  4 | import { useIntl } from 'react-intl';

Import trace for requested module:
./src/pages/organize/[orgId]/people/views/[viewId].tsx
```

**Comment by richardolsson** [comment]
Everything seems to be working here at least. The errors about missing localizations are not blocking (although they should be fixed, but you don't have to worry about that). I believe you're just missing a dependency. Please make sure to run `yarn install` after pulling, so that any new dependencies (in this case `lodash.isequal`) is installed.

**Comment by bimtauer** [comment]
Yeah `yarn install` makes perfect sense 🙈. But the real problem for me seemed to be access to the dev database. I will try again later.

**Comment by richardolsson** [comment]
I don't think there are any problems with access to the dev API. Try http://localhost:3000/organize/1/people/views and it should work. If you ever get a 404, just try refreshing. It may be that the API access token expired and the backend incorrectly (and temporarily, while refreshing) returned 404.

**Comment by richardolsson** [comment]
Are you still working on this @bimtauer?

**Comment by bimtauer** [comment]
@richardolsson I am yes. Sorry for the silence, had covid in between and was generally drained.

**Comment by richardolsson** [comment]
No stress @bimtauer! Just wanted to make sure we're in sync!

![sync](https://media.giphy.com/media/lS7otnEgehFrnxz7Fw/giphy.gif)

**Comment by bimtauer** [comment]
So I've picked this up again, and I might need a little tip in the right direction how to properly use `useGridApiRef`. 
Opened a draft here: https://github.com/zetkin/app.zetkin.org/pull/570

I'm trying to use `gridApiRef.current.getDataAsCsv()` but get `TypeError: gridApiRef.current.getDataAsCsv is not a function`

**Comment by richardolsson** [comment]
@bimtauer I believe you have to pass your `gridApiRef` instance to the `apiRef` property of the grid. See `apiRef` here: https://v4.mui.com/api/data-grid/data-grid-pro

**Comment by bimtauer** [comment]
So I assume I need to create the `gridApiRef` on the level of [[viewId].tsx](https://github.com/bimtauer/app.zetkin.org/blob/480-csv-export/src/pages/organize/%5BorgId%5D/people/views/%5BviewId%5D.tsx#L94-L95) and pass it to both `ViewDataTable` and `SingleViewLayout`?

**Comment by richardolsson** [comment]
> So I assume I need to create the `gridApiRef` on the level of [[viewId].tsx](https://github.com/bimtauer/app.zetkin.org/blob/480-csv-export/src/pages/organize/%5BorgId%5D/people/views/%5BviewId%5D.tsx#L94-L95) and pass it to both `ViewDataTable` and `SingleViewLayout`? Got to modify their interfaces for that 😬

Yes maybe that's the best way to do it, or maybe there's another way. I suggest we move this discussion to Slack.

**Comment by richardolsson** [comment]
Closing this as superseded by #872
