### ISSUE TITLE
Separate ports for devserver and playwright

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#500]
### Description
Sometimes when I'm running playwright tests, they fail because port 3000 is already allocated. This happens when I'm running the devserver simultaneously. I thought this was not supposed to happen, since every test instance runs on a random port.

### Expected Behaviour
Playwright tests should never run on port 3000

### Actual Behaviour
Playwright tests sometimes (I haven't been able to see a pattern) runs on port 3000.

### Steps to reproduce
1. Start devserver with `yarn devserver`
2. In a separate shell, start playwright with `yarn playwright`

### Playwright log
```
app.zetkin.org $ yarn playwright
yarn run v1.22.10
$ cross-env NODE_ENV=production playwright test
Using config at /Users/richardolsson/src/zetkin/product/app.zetkin.org/playwright.config.ts
info  - Loaded env from /Users/richardolsson/src/zetkin/product/app.zetkin.org/.env.production
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types  
warn  - The Next.js plugin was not detected in your ESLint configuration. See https://nextjs.org/docs/basic-features/eslint#migrating-existing-config
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data  
info  - Generating static pages (2/2)
info  - Finalizing page optimization  

Page                                                                        Size     First Load JS
┌ λ /                                                                       2.23 kB         125 kB
├   /_app                                                                   0 B             122 kB
├ ○ /404 (867 ms)                                                           2.02 kB         130 kB
├ λ /api/[...path]                                                          0 B             122 kB
├ λ /api/breadcrumbs                                                        0 B             122 kB
├ λ /api/views/createNew                                                    0 B             122 kB
├ λ /login                                                                  255 B           123 kB
├ λ /logout                                                                 254 B           123 kB
├ λ /organize/[orgId]/campaigns                                             3.44 kB         173 kB
├ λ /organize/[orgId]/campaigns/[campId]                                    7.5 kB          268 kB
├ λ /organize/[orgId]/campaigns/[campId]/calendar                           2.29 kB         235 kB
├ λ /organize/[orgId]/campaigns/[campId]/calendar/tasks/[taskId]            1.13 kB         255 kB
├ λ /organize/[orgId]/campaigns/[campId]/calendar/tasks/[taskId]/assignees  28.8 kB         283 kB
├ λ /organize/[orgId]/campaigns/calendar                                    1.56 kB         191 kB
├ λ /organize/[orgId]/people/views                                          4.91 kB         172 kB
└ λ /organize/[orgId]/people/views/[viewId]                                 72.8 kB         254 kB
+ First Load JS shared by all                                               122 kB
  ├ chunks/framework.fb2dd7.js                                              42.4 kB
  ├ chunks/main.1f2c59.js                                                   23.6 kB
  ├ chunks/pages/_app.6515c3.js                                             54.5 kB
  ├ chunks/webpack.f7b6c4.js                                                1.84 kB
  └ css/02443d1bff45fb432348.css                                            190 B

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)


Running 15 tests using 4 workers

[HPM] Proxy created: /  -> http://api.dev.zetkin.org
  ✘  tests/organize/campaign-detail/action-buttons.spec.ts:46:9 › Campaign action buttons › edit campaign dialog › allows users t
  -  tests/organize/campaign-detail/action-buttons.spec.ts:91:9 › Campaign action buttons › edit campaign dialog › shows error al
[HPM] Proxy created: /  -> http://api.dev.zetkin.org
[HPM] Proxy created: /  -> http://api.dev.zetkin.org
[HPM] Proxy created: /  -> http://api.dev.zetkin.org
  ✓  tests/organize/campaign-detail/speed-dial.spec.ts:58:9 › Single campaign page › creating a task from speed dial › user can c
[HPM] Proxy created: /  -> http://api.dev.zetkin.org
  ✓  tests/organize/campaigns-list/list-campaigns.spec.ts:25:5 › All campaigns page › shows list of campaigns  (11s)
  ✓  tests/organize/campaigns-list/speed-dial.spec.ts:42:9 › All campaigns page speed dial › allows user to create a campiagn › u
  ✓  tests/organize/people/views/create-new-view.spec.ts:30:5 › Views list page › shows an error dialog if there is an error crea
  ✓  tests/organize/people/views/view-detail.spec.ts:26:5 › View detail page › displays view title and content to the user (3s)
  ✓  tests/organize/people/views/create-new-view.spec.ts:52:5 › Views list page › creates a new view with two columns for first a
     tests/organize/campaigns-list/speed-dial.spec.ts:77:9 › All campaigns page speed dial › allows user to create a campiagn › s
     tests/organize/campaign-detail/speed-dial.spec.ts:91:9 › Single campaign page › creating a task from speed dial › shows erro
     tests/organize/people/views/views-list.spec.ts:26:9 › Views list page › views list table › informs user they do not have any
     tests/organize/task-detail/action-buttons.spec.ts:29:9 › Task action buttons › edit task dialog › allows users to edit task 
  ✓  tests/organize/campaigns-list/speed-dial.spec.ts:77:9 › All campaigns page speed dial › allows user to create a campiagn › s
  ✓  tests/organize/campaign-detail/speed-dial.spec.ts:91:9 › Single campaign page › creating a task from speed dial › shows erro
  ✓  tests/organize/people/views/views-list.spec.ts:26:9 › Views list page › views list table › informs user they do not have any
  ✓  tests/organize/task-detail/action-buttons.spec.ts:29:9 › Task action buttons › edit task dialog › allows users to edit task 
4:23)
    at Object.apiResolver (/Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/next/dist/server/api-utils.js:101:9)
    at Server.handleApiRequest (/Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/next/dist/server/next-server.js:770:9)
    at Object.fn (/Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/next/server/next-server.ts:975:24)
    at Router.execute (/Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/next/server/router.ts:346:21)
    at Server.run (/Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/next/server/next-server.ts:1229:20)
    at Server.handleRequest (/Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/next/dist/server/next-server.js:292:20)
  ✓  tests/organize/people/views/views-list.spec.ts:40:9 › Views list page › views list table › displays available views to the u
     tests/organize/people/views/views-list.spec.ts:65:9 › Views list page › views list table › navigates to view page when user 
  ✓  tests/organize/people/views/views-list.spec.ts:65:9 › Views list page › views list table › navigates to view page when user 
  ✓  tests/organize/task-detail/action-buttons.spec.ts:73:9 › Task action buttons › edit task dialog › shows error alert if serve
    at Object.queryFn (/Users/richardolsson/src/zetkin/product/app.zetkin.org/.next/server/pages/organize/[orgId]/people/views/[viewId].js:105:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)


  1) tests/organize/campaign-detail/action-buttons.spec.ts:46:9 › Campaign action buttons › edit campaign dialog › allows users to edit campaign details 

    Error: listen EADDRINUSE: address already in use :::3000

        at Server.setupListenHandle [as _listen2] (node:net:1334:16)
        at listenInCluster (node:net:1382:12)
        at Server.listen (node:net:1469:7)
        at Function.listen (/Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/express/lib/application.js:618:24)
        at start (/Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/moxy/lib/index.js:148:26)
        at Object._test.test.extend.moxy.auto [as fn] (/Users/richardolsson/src/zetkin/product/app.zetkin.org/playwright/fixtures/next.ts:89:9)
        at Fixture.setup (/Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/@playwright/test/lib/fixtures.js:74:73)
        at FixtureRunner.setupFixtureForRegistration (/Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/@playwright/test/lib/fixtures.js:315:19)
        at Fixture.setup (/Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/@playwright/test/lib/fixtures.js:58:37)
        at FixtureRunner.setupFixtureForRegistration (/Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/@playwright/test/lib/fixtures.js:315:19)
        at FixtureRunner.resolveParametersAndRunHookOrTest (/Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/@playwright/test/lib/fixtures.js:287:56)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at WorkerRunner._runTestWithBeforeHooks (/Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/@playwright/test/lib/workerRunner.js:478:7)

  2) tests/organize/campaign-detail/action-buttons.spec.ts:91:9 › Campaign action buttons › edit campaign dialog › shows error alert if server error on request 

    Error: listen EADDRINUSE: address already in use :::3000

        at Server.setupListenHandle [as _listen2] (node:net:1334:16)
        at listenInCluster (node:net:1382:12)
        at Server.listen (node:net:1469:7)
        at Function.listen (/Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/express/lib/application.js:618:24)
        at start (/Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/moxy/lib/index.js:148:26)
        at Object._test.test.extend.moxy.auto [as fn] (/Users/richardolsson/src/zetkin/product/app.zetkin.org/playwright/fixtures/next.ts:89:9)
        at Fixture.setup (/Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/@playwright/test/lib/fixtures.js:74:73)
        at FixtureRunner.setupFixtureForRegistration (/Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/@playwright/test/lib/fixtures.js:315:19)
        at Fixture.setup (/Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/@playwright/test/lib/fixtures.js:58:37)
        at FixtureRunner.setupFixtureForRegistration (/Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/@playwright/test/lib/fixtures.js:315:19)
        at FixtureRunner.resolveParametersAndRunHookOrTest (/Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/@playwright/test/lib/fixtures.js:287:56)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at WorkerRunner._runTestWithBeforeHooks (/Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/@playwright/test/lib/workerRunner.js:478:7)

  Slow test: tests/organize/campaign-detail/speed-dial.spec.ts (15s)

  1 failed
    tests/organize/campaign-detail/action-buttons.spec.ts:46:9 › Campaign action buttons › edit campaign dialog › allows users to edit campaign details 
  1 skipped
  13 passed (24s)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
app.zetkin.org $ 

```

**Comment by richardolsson** [comment]
I think trying to fix this is actually moot, because playwright and the dev server can't be successfully run side by side anyway (since the NEXT.js build cache will interfere).
