### ISSUE TITLE
Tags Manager duplicate keys

### ISSUE THREAD

**Issue by ev-sc** [zetkin/app.zetkin.org#651]
TagsManager needs some attention w.r.t. errors such as this:

```
    console.error
      Warning: Encountered two children with the same key, `4`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
          at div
          at StyledComponent (/home/everin/repos/app.zetkin.org/node_modules/@material-ui/styles/styled/styled.js:95:28)
          at TagsList (/home/everin/repos/app.zetkin.org/src/components/organize/TagsManager/TagsList.tsx:13:9)
          at div
          at StyledComponent (/home/everin/repos/app.zetkin.org/node_modules/@material-ui/styles/styled/styled.js:95:28)
          at div
          at StyledComponent (/home/everin/repos/app.zetkin.org/node_modules/@material-ui/styles/styled/styled.js:95:28)
          at ZetkinSection (/home/everin/repos/app.zetkin.org/src/components/ZetkinSection.tsx:10:3)
          at TagsManager (/home/everin/repos/app.zetkin.org/src/components/organize/TagsManager/index.tsx:23:3)
          at QueryClientProvider (/home/everin/repos/app.zetkin.org/node_modules/react-query/lib/react/QueryClientProvider.js:45:21)
          at IntlProvider (/home/everin/repos/app.zetkin.org/node_modules/react-intl/src/components/provider.js:81:47)
          at MuiPickersUtilsProvider (/home/everin/repos/app.zetkin.org/node_modules/@material-ui/src/MuiPickersUtilsProvider.tsx:16:3)
          at ThemeProvider (/home/everin/repos/app.zetkin.org/node_modules/@material-ui/styles/ThemeProvider/ThemeProvider.js:48:24)
          at ZetkinAppProviders (/home/everin/repos/app.zetkin.org/src/utils/testing/index.tsx:19:35)

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:67:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:43:5)
      at warnOnInvalidKey (node_modules/react-dom/cjs/react-dom.development.js:13620:11)
      at reconcileChildrenArray (node_modules/react-dom/cjs/react-dom.development.js:13651:21)
      at reconcileChildFibers (node_modules/react-dom/cjs/react-dom.development.js:14125:14)
      at reconcileChildren (node_modules/react-dom/cjs/react-dom.development.js:16990:28)
      at updateHostComponent (node_modules/react-dom/cjs/react-dom.development.js:17632:3)
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:19080:14)
```

**Comment by richardolsson** [comment]
I just noticed this as well. I was very happy to find you had created an issue and scheduled it for R33. Makes me feel like we're very in sync. 😊

**Comment by richardolsson** [comment]
This may or may not still be the case. Anyone taking on this issue should verify that it's reproducible before spending too much time on it.
